name: scapia_x_sdk
description: "Scapia X bank sdk"
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: 2.1.8
  json_serializable: 6.8.0
  json_annotation: 4.9.0
  get_it: 7.7.0
  dio: 5.4.3+1
  curl_logger_dio_interceptor: 1.0.0


  newrelic_mobile: 1.0.9

  # Firebase
  firebase_app_check: 0.3.0+2

  get: 4.6.6
  package_info_plus: 7.0.0
  device_info_plus: ^9.0.2
  get_secure_storage: 1.0.4
  flutter_dotenv: 5.1.0
  rxdart: 0.27.7
  shared_preferences_plus:
    git:
      url: git@github.com:scapia/shared_preferences_plus.git
      ref: 0.0.5
  bank_base_sdk:
    path: ../bank-base-sdk
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0
  build_runner: 2.4.11

flutter:
  plugin:
    platforms:
      android:
        package: com.example.scapia_x_sdk
        pluginClass: ScapiaXSdkPlugin
      ios:
        pluginClass: ScapiaXSdkPlugin